name: stupid
description: A dart package to communicate with stupid-backend.
version: 0.0.4
repository: https://github.com/CalebQ42/stupid-dart

environment:
  sdk: '>=2.19.4 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1

dependencies:
  http: ^0.13.5
  platform_info: ^3.2.0
  uuid: ^3.0.7
