name: stupid
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/CalebQ42/stupid-dart

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
