name: stupid
description: A dart package to communicate with stupid-backend.
version: 0.1.1
repository: https://github.com/CalebQ42/stupid-dart

environment:
  sdk: '>=2.19.4 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4

dependencies:
  http: ^1.1.0
  platform_info: ^4.0.0
  uuid: ^3.0.7
